/**
 * Example Application
 * ===================
 * Demonstrates a C application using the Framework SDK with NAH.
 * Uses standalone manifest.nah file (generated by `nah manifest generate`).
 *
 * This single example replaces the former app_a and app_b, which were
 * nearly identical. Version requirement differences are demonstrated
 * in the CMakeLists.txt and documentation, not in separate apps.
 */

#include <framework/framework.h>
#include <stdio.h>
#include <stdlib.h>

static int on_start(framework_ctx_t* ctx, void* user_data) {
    (void)user_data;

    FW_INFO(ctx, "Application starting");
    FW_INFO(ctx, "Running as: %s v%s",
            framework_get_app_id(ctx),
            framework_get_app_version(ctx));
    FW_DEBUG(ctx, "App root: %s", framework_get_app_root(ctx));
    FW_DEBUG(ctx, "SDK root: %s", framework_get_sdk_root(ctx));

    /* Load SDK resource */
    size_t theme_size = 0;
    char* theme = framework_load_sdk_resource(ctx, "default_theme.json", &theme_size);
    if (theme) {
        FW_INFO(ctx, "Loaded SDK theme (%zu bytes)", theme_size);
        free(theme);
    }

    /* Load app resource */
    size_t config_size = 0;
    char* config = framework_load_app_resource(ctx, "config.json", &config_size);
    if (config) {
        FW_INFO(ctx, "Loaded app config (%zu bytes)", config_size);
        free(config);
    }

    FW_INFO(ctx, "Application completed successfully");
    return 0;
}

static void on_stop(framework_ctx_t* ctx, void* user_data) {
    (void)user_data;
    FW_INFO(ctx, "Application shutting down");
}

int main(int argc, char* argv[]) {
    (void)argc;
    (void)argv;

    printf("Example App v1.0.0\n");
    printf("==================\n\n");

    if (framework_is_nah_managed()) {
        printf("Running in NAH-managed environment\n");
        printf("  NAH_APP_ID=%s\n", getenv("NAH_APP_ID") ? getenv("NAH_APP_ID") : "(not set)");
        printf("  NAH_APP_ROOT=%s\n", getenv("NAH_APP_ROOT") ? getenv("NAH_APP_ROOT") : "(not set)");
        printf("  NAH_NAK_ID=%s\n", getenv("NAH_NAK_ID") ? getenv("NAH_NAK_ID") : "(not set)");
    } else {
        printf("Running standalone (not NAH-managed)\n");
    }
    printf("\n");

    fw_init_options_t opts = {
        .app_id = NULL,
        .app_root = NULL,
        .log_level = FW_LOG_DEBUG,
        .use_nah_env = true
    };

    framework_ctx_t* ctx = framework_init(&opts);
    if (!ctx) {
        fprintf(stderr, "Failed to initialize framework\n");
        return 1;
    }

    fw_lifecycle_callbacks_t callbacks = {
        .on_start = on_start,
        .on_stop = on_stop,
        .on_config_reload = NULL
    };

    int result = framework_run(ctx, &callbacks, NULL);
    framework_shutdown(ctx);

    return result;
}
